server:
  port: 8080

spring:
  application:
    name: auth-service

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  endpoint:
    prometheus:
      enabled: true